name: Deploy to Namecheap

on:
  push:
    branches:
      - main  # Déploie automatiquement quand on push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy via SFTP with SSH Key
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        local_path: './*'
        remote_path: '/home/${{ secrets.FTP_USERNAME }}/tom.better-investor.co'
        sftp_only: true
        args: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'
